services:
  mysqldb:
    ports:
      - "3307:3306"

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Customer.Api/Dockerfile

volumes:
  mysql_data:
